name: CI/CD Workflow

# Trigger the workflow on push or PR to main
on:
  workflow_dispatch: # Manual trigger via GitHub UI
  push: # Automatically triggered on push to main branch
    branches:
      - main
  pull_request: # Automatically triggered on PR to main branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Uses GitHub-hosted Ubuntu runner
    steps:
      - uses: actions/checkout@v3 # Checks out repository code
      - name: Set up Node.js
        uses: actions/setup-node@v3 # Sets up Node.js environment
        with:
          node-version: "22.x"
          cache: "npm" # Caches npm dependencies
      - name: Install dependencies
        run: npm ci # Installs dependencies via npm
      - name: Simulate build
        run: echo "Simulate build" # Placeholder for actual build command

  test:
    needs: build # This job runs after the build job completes
    runs-on: ubuntu-latest
    steps:
      # Similar setup to build job
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          echo "Running tests..."
          npm run test  # Runs the test script from package.json

  publish:
    needs: test # This job runs after the test job completes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Sets up Docker build system
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # Logs in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Uses repository secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4 # Builds and pushes Docker image
        with:
          context: .
          push: true
          tags: huai99/education-space:latest # Tags the Docker image