version: 2.1

orbs:
  node: circleci/node@5.0.1


build:
  docker:
    - image: cimg/node:16.10
  steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run: |
        echo "Installing dependencies..."
        npm install

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build

executor: docker/docker