version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.4.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USER/container-assignment:latest .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_TOKEN
            docker push $DOCKER_USER/container-assignment:latest


workflows:
  build-and-push:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test